# Generated by Django 4.2.18 on 2025-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (160 characters max)', max_length=160),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='static/blog/images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='E.g. how-to-build-a-castle', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(upload_to='static/blog/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/authors/'),
        ),
        # Removed AlterModelTable operations - tables already have correct names
    ]
